//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        public int BOOKING_ID { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public Nullable<int> ROUTE_ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public Nullable<System.DateTime> DATE_BOOKING { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<int> COUNT_SEATS { get; set; }
    
        public virtual CLIENTS CLIENTS { get; set; }
        public virtual ROUTE ROUTE { get; set; }
        public virtual TRAVEK_COMPANY TRAVEK_COMPANY { get; set; }
    }
}
