//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTS()
        {
            this.BOOKING = new HashSet<BOOKING>();
        }
    
        public int CLIENT_ID { get; set; }
        public string FIO { get; set; }
        public Nullable<int> PASSPORT_SERIA { get; set; }
        public Nullable<int> PASSPORT_NUMBER { get; set; }
        public string NUMBER { get; set; }
        public Nullable<System.DateTime> DATE_BIRTHDAY { get; set; }
        public Nullable<bool> MALE { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> ROLE_ID { get; set; }
        public string FriendlyName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKING { get; set; }
    }
}
