//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROUTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROUTE()
        {
            this.BOOKING = new HashSet<BOOKING>();
        }
    
        public int ROUTE_ID { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public Nullable<int> TRANSPORT_ID { get; set; }
        public string WHERE_ON { get; set; }
        public string WHERE_OF { get; set; }
        public Nullable<System.DateTime> DATE_ON { get; set; }
        public Nullable<System.DateTime> DATE_OFF { get; set; }
        public Nullable<System.TimeSpan> TIME_ROUTE { get; set; }
        public Nullable<decimal> PRICE_ROUTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKING { get; set; }
        public virtual TRANSPORT TRANSPORT { get; set; }
        public virtual TRAVEK_COMPANY TRAVEK_COMPANY { get; set; }
    }
}
