//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSPORT()
        {
            this.ROUTE = new HashSet<ROUTE>();
        }
    
        public int TRANSPORT_ID { get; set; }
        public Nullable<bool> TYPE_TRANSPORT { get; set; }
        public Nullable<int> NUM_SEATS { get; set; }
        public string NAME_TRANSPORT { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROUTE> ROUTE { get; set; }
        public virtual TRAVEK_COMPANY TRAVEK_COMPANY { get; set; }
    }
}
