//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int USER_ID { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> ROLE_ID { get; set; }
        public string FriendlyName { get; set; }
    }
}
